version: '3.9'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www/
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "8885:80"
        container_name: project_nginx
        depends_on:
            - app

    app:
        build:
            args:
                user: ${USER}
                uid: ${UID}
            context: .
            dockerfile: docker/app/Dockerfile
        volumes:
            - ./:/var/www/
        container_name: project_app
        depends_on:
            - db

    db:
        image: postgres:14.12
        restart: always
        volumes:
            - ./docker/db/data:/var/lib/postgresql/data
            - ./docker/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        ports:
            - "8886:5432"
        container_name: project_db
